apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  POSTGRES_DB_HOST: "postgres"
  POSTGRES_DB_TOOL: "tool-db"
  POSTGRES_DB_LOAN: "loan-db"
  POSTGRES_DB_CLIENT: "client-db"
  POSTGRES_DB_BILL: "bill-db"
  POSTGRES_DB_KARDEX: "kardex-db"
  POSTGRES_DB_REPORT: "report-db"